# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  INSTAGRAM_ID: 9ffba2c2159249609f55f81ecae51022
  INSTAGRAM_SECRET: ce57610694cf4523bfeb0f158c480469
  ARTSY_ID: c7c4a1f99f262a3ae9f8
  ARTSY_SECRECT: a35ded27404562fbfa5e39edfd6280ab
